[[redirects]]
    from="/*"
    to="/index.html"
    status = 200

[build]
    command = "npm run build"
    publish = "dist"
    functions = "netlify/functions/"
    ignore = "/bin/false"

[[headers]]
    for = "/*"
        [headers.values]
        Content-Security-Policy = "frame-ancestors 'self'"
