[[redirects]]
    from="/*"
    to="/index.html"
    status = 200

[build]
    command = "npm run build"
    publish = "frontend/dist"
    functions = "frontend/netlify/functions/"

[[headers]]
    for = "/*"
        [headers.values]
        Content-Security-Policy = "frame-ancestors 'self'"
